yamlApplicationConfig:
  kafka:
    clusters:
      - name: local
        bootstrapServers:  my-confluent-cp-kafka:9092
  auth:
    type: disabled
  management:
    health:
      ldap:
        enabled: false